site_name: 'Vapor Cloud'
pages:
- Home: 'index.md'
- Configuring deployment:
    - 'Introduction to .vcloud.yml': 'configuring-deployment/introduction-to-vcloud.yml.md'
    - 'General': 'configuring-deployment/general.md'
    - 'Vapor': 'configuring-deployment/vapor.md'
    - 'Blank': 'configuring-deployment/blank.md'
