site_name: 'Vapor Cloud'
copyright: 'Copyright &copy; 2017 Vapor Cloud'
markdown_extensions:
      - admonition
      - codehilite(guess_lang=true)
      - footnotes
      - meta
      - toc(permalink=true)

theme: 'material'

extra_css:
      - 'stylesheets/extra.css'


repo_url: https://github.com/vapor/vapor

extra:
      logo: 'images/white-cloud-icon.svg'
      social:
        - type: 'twitter'
          link: 'https://twitter.com/@codevapor'
        - type: 'slack'
          link: 'http://vapor.team/'

pages:
- Home: 'index.md'
- VCloud CLI: 'vcloud-cli.md'
- API Documentation:
    - 'Introduction': 'api/introduction.md'
    - 'Admin API': 'api/admin-api.md'
- Configuring deployment:
    - 'Introduction to .vcloud.yml': 'configuring-deployment/introduction-to-vcloud.yml.md'
    - 'General': 'configuring-deployment/general.md'
    - 'Vapor': 'configuring-deployment/vapor.md'
    - 'Blank': 'configuring-deployment/blank.md'
