site_name: 'Vapor Cloud Docs'
copyright: 'Copyright &copy; 2017 Qutheory, LLC'
markdown_extensions:
      - admonition
      - codehilite(guess_lang=true)
      - footnotes
      - meta
      - toc(permalink=true)

theme: 'material'
theme_dir: 'vapor-material'

repo_url: https://github.com/vapor/vapor

extra:
      logo: 'images/white-cloud-icon.svg'
      social:
        - type: 'twitter'
          link: 'https://twitter.com/@codevapor'
        - type: 'slack'
          link: 'http://vapor.team/'
      font:
        text: 'Roboto Slab'
        code: 'Source Code Pro'

extra_css:
  - 'stylesheets/extra.css'

pages:
- Overview: 'index.md'
- Architecture:
    - 'Core principles': 'architecture/core-principles.md'
- Toolbox:
    - 'Install': 'toolbox/install.md'
    - 'Getting Started': 'toolbox/getting-started.md'
- cloud.yml:
    - 'General': 'configuration/general.md'
    - Vapor:
        - 'Basic': 'configuration/vapor/basic.md'
        - 'Custom config': 'configuration/vapor/custom-config.md'
    - 'Blank': 'configuration/blank.md'
- APIs:
    - 'Introduction': 'api/introduction.md'
    - 'Admin API': 'api/admin-api.md'
    - 'Application API': 'api/application-api.md'
- Advanced:
    - General:
        - 'About our server setup': 'server-setup/general/about-our-server-setup.md'
        - 'How do cronjobs work': 'server-setup/general/how-do-cronjobs-work.md'
        - 'Sending E-mails (SMTP)': 'server-setup/general/sending-emails.md'
        - 'Using private git repository': 'server-setup/general/using-private-git.md'
        - 'Running load tests': 'server-setup/general/load-testing.md'
        - 'TLS With Lets Encrypt': 'server-setup/general/tls-with-letsencrypt.md'
    - Loadbalancer:
        - 'SSL/TLS': 'server-setup/loadbalancer/ssl-tls.md'
    - Storage:
        - 'Store files on S3': 'server-setup/storage/store-files-on-s3.md'
        - 'Accessing files through CDN': 'server-setup/storage/accessing-files-through-cdn.md'
    - Security:
        - 'Responsibilities': 'server-setup/security/responsibilities.md'
        - 'Your responsibilities': 'server-setup/security/your-responsibilities.md'
        - 'Vapor Cloud security': 'server-setup/security/vapor-cloud-security.md'
